repo_url: "https://github.com/warllemedicao/Voz_styllett2.git"
repo_dir: "/content/Super_voz"
project_subdir: "super_Voz"

styletts2_repo: "https://github.com/yl4579/StyleTTS2.git"
styletts2_dir: "/content/StyleTTS2"

drive_project_dir: "/content/drive/MyDrive/super_Voz"
raw_audio_candidates:
  - "/content/drive/MyDrive/super_Voz/Audios_brutos"
  - "/content/drive/MyDrive/super_Voz/Audios_Brutos"
  - "/content/drive/MyDrive/Treinamento_voz/Audios_brutos"
  - "/content/drive/MyDrive/Treinamento_voz/Audios_Brutos"
  - "/content/drive/MyDrive/Audios_brutos"
  - "/content/drive/MyDrive/Audios_Brutos"
processed_audio_candidates:
  - "/content/drive/MyDrive/super_Voz/Audios_processados"
  - "/content/drive/MyDrive/Treinamento_voz/Audios_processados"
  - "/content/drive/MyDrive/Audios_processados"

speaker: "0"
sample_rate: 24000
val_ratio: 0.05
phonemize: true
phonemizer_language: "pt-br"

epochs: 50
batch_size: 8
max_len: 400
save_freq: 5
log_interval: 10

# Para Colab comum, deixar joint_epoch maior que epochs reduz risco de OOM,
# pulando a fase SLM adversarial mais pesada.
joint_epoch: 999
diff_epoch: 10
